//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.1433
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonSoft.Services.JobSchedule.ClientProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<string, object> ArgumentField;
        
        private string AssemblyNameField;
        
        private string ClassNameField;
        
        private string DescriptionField;
        
        private string GroupField;
        
        private string NameField;
        
        private bool RequestsRecoveryField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Argument
        {
            get
            {
                return this.ArgumentField;
            }
            set
            {
                this.ArgumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyName
        {
            get
            {
                return this.AssemblyNameField;
            }
            set
            {
                this.AssemblyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName
        {
            get
            {
                return this.ClassNameField;
            }
            set
            {
                this.ClassNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequestsRecovery
        {
            get
            {
                return this.RequestsRecoveryField;
            }
            set
            {
                this.RequestsRecoveryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frequency", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.Daily))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.Monthly))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.Weekly))]
    public partial class Frequency : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Daily", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class Daily : JasonSoft.Services.JobSchedule.ClientProxy.Frequency
    {
        
        private int RepeatedDaysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatedDays
        {
            get
            {
                return this.RepeatedDaysField;
            }
            set
            {
                this.RepeatedDaysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Monthly", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class Monthly : JasonSoft.Services.JobSchedule.ClientProxy.Frequency
    {
        
        private int DayOfMonthField;
        
        private int RepeatedMonthsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayOfMonth
        {
            get
            {
                return this.DayOfMonthField;
            }
            set
            {
                this.DayOfMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatedMonths
        {
            get
            {
                return this.RepeatedMonthsField;
            }
            set
            {
                this.RepeatedMonthsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weekly", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class Weekly : JasonSoft.Services.JobSchedule.ClientProxy.Frequency
    {
        
        private System.DayOfWeek DayOfWeekField;
        
        private int RepeatedWeeksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek DayOfWeek
        {
            get
            {
                return this.DayOfWeekField;
            }
            set
            {
                this.DayOfWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatedWeeks
        {
            get
            {
                return this.RepeatedWeeksField;
            }
            set
            {
                this.RepeatedWeeksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trigger", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.RecurvedTrigger))]
    public partial class Trigger : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GroupField;
        
        private string JobGroupNameField;
        
        private string JobNameField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGroupName
        {
            get
            {
                return this.JobGroupNameField;
            }
            set
            {
                this.JobGroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName
        {
            get
            {
                return this.JobNameField;
            }
            set
            {
                this.JobNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurvedTrigger", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class RecurvedTrigger : JasonSoft.Services.JobSchedule.ClientProxy.Trigger
    {
        
        private JasonSoft.Services.JobSchedule.ClientProxy.DailyFrequency DailyFrequencyField;
        
        private System.Nullable<System.DateTime> EndDateUTCField;
        
        private JasonSoft.Services.JobSchedule.ClientProxy.Frequency FrequencyField;
        
        private System.DateTime StartDateUTCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.DailyFrequency DailyFrequency
        {
            get
            {
                return this.DailyFrequencyField;
            }
            set
            {
                this.DailyFrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDateUTC
        {
            get
            {
                return this.EndDateUTCField;
            }
            set
            {
                this.EndDateUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.Frequency Frequency
        {
            get
            {
                return this.FrequencyField;
            }
            set
            {
                this.FrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateUTC
        {
            get
            {
                return this.StartDateUTCField;
            }
            set
            {
                this.StartDateUTCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyFrequency", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.OnceDailyFrequency))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JasonSoft.Services.JobSchedule.ClientProxy.RepeatedDailyFrequency))]
    public partial class DailyFrequency : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnceDailyFrequency", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class OnceDailyFrequency : JasonSoft.Services.JobSchedule.ClientProxy.DailyFrequency
    {
        
        private System.TimeSpan OccurTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan OccurTime
        {
            get
            {
                return this.OccurTimeField;
            }
            set
            {
                this.OccurTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepeatedDailyFrequency", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class RepeatedDailyFrequency : JasonSoft.Services.JobSchedule.ClientProxy.DailyFrequency
    {
        
        private System.DateTime EndingAtUTCField;
        
        private int RepeatedMinutesField;
        
        private System.DateTime StartingAtUTCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndingAtUTC
        {
            get
            {
                return this.EndingAtUTCField;
            }
            set
            {
                this.EndingAtUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatedMinutes
        {
            get
            {
                return this.RepeatedMinutesField;
            }
            set
            {
                this.RepeatedMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartingAtUTC
        {
            get
            {
                return this.StartingAtUTCField;
            }
            set
            {
                this.StartingAtUTCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobHistory", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class JobHistory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BeginDateUTCField;
        
        private System.Nullable<System.DateTime> EndDateUTCField;
        
        private int IDField;
        
        private string InstanceNameField;
        
        private string JobGroupNameField;
        
        private string JobNameField;
        
        private string MessageField;
        
        private JasonSoft.Services.JobSchedule.ClientProxy.Mode ModeField;
        
        private int PeriodField;
        
        private JasonSoft.Services.JobSchedule.ClientProxy.State StateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginDateUTC
        {
            get
            {
                return this.BeginDateUTCField;
            }
            set
            {
                this.BeginDateUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDateUTC
        {
            get
            {
                return this.EndDateUTCField;
            }
            set
            {
                this.EndDateUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceName
        {
            get
            {
                return this.InstanceNameField;
            }
            set
            {
                this.InstanceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGroupName
        {
            get
            {
                return this.JobGroupNameField;
            }
            set
            {
                this.JobGroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName
        {
            get
            {
                return this.JobNameField;
            }
            set
            {
                this.JobNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.Mode Mode
        {
            get
            {
                return this.ModeField;
            }
            set
            {
                this.ModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period
        {
            get
            {
                return this.PeriodField;
            }
            set
            {
                this.PeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.State State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mode", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public enum Mode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Automatic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manual = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public enum State : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StopManually = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobState", Namespace="http://schemas.datacontract.org/2004/07/JasonSoft.Services.JobSchelude")]
    public partial class JobState : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string JobGroupNameField;
        
        private string JobNameField;
        
        private JasonSoft.Services.JobSchedule.ClientProxy.State LastFireStateField;
        
        private System.Nullable<System.DateTime> NextFireTimeUTCField;
        
        private System.Nullable<System.DateTime> PreviousFireTimeUTCField;
        
        private string ProgressField;
        
        private JasonSoft.Services.JobSchedule.ClientProxy.State StateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobGroupName
        {
            get
            {
                return this.JobGroupNameField;
            }
            set
            {
                this.JobGroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName
        {
            get
            {
                return this.JobNameField;
            }
            set
            {
                this.JobNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.State LastFireState
        {
            get
            {
                return this.LastFireStateField;
            }
            set
            {
                this.LastFireStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextFireTimeUTC
        {
            get
            {
                return this.NextFireTimeUTCField;
            }
            set
            {
                this.NextFireTimeUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PreviousFireTimeUTC
        {
            get
            {
                return this.PreviousFireTimeUTCField;
            }
            set
            {
                this.PreviousFireTimeUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Progress
        {
            get
            {
                return this.ProgressField;
            }
            set
            {
                this.ProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JasonSoft.Services.JobSchedule.ClientProxy.State State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JasonSoft.Services.JobSchedule.ClientProxy.IScheduleService")]
    public interface IScheduleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/ScheduleJob", ReplyAction="http://tempuri.org/IScheduleService/ScheduleJobResponse")]
        System.DateTime ScheduleJob(JasonSoft.Services.JobSchedule.ClientProxy.Job job, JasonSoft.Services.JobSchedule.ClientProxy.Trigger trigger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetJob", ReplyAction="http://tempuri.org/IScheduleService/GetJobResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.Job GetJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetJobsByGroup", ReplyAction="http://tempuri.org/IScheduleService/GetJobsByGroupResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.Job[] GetJobsByGroup(string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/CreateJob", ReplyAction="http://tempuri.org/IScheduleService/CreateJobResponse")]
        void CreateJob(JasonSoft.Services.JobSchedule.ClientProxy.Job job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/DeleteJob", ReplyAction="http://tempuri.org/IScheduleService/DeleteJobResponse")]
        void DeleteJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/DeleteJobsByGroup", ReplyAction="http://tempuri.org/IScheduleService/DeleteJobsByGroupResponse")]
        void DeleteJobsByGroup(string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/UpdateJob", ReplyAction="http://tempuri.org/IScheduleService/UpdateJobResponse")]
        void UpdateJob(string oldJobName, string oldJobGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Job newJob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetTrigger", ReplyAction="http://tempuri.org/IScheduleService/GetTriggerResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.Trigger GetTrigger(string triggerName, string triggerGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetTriggersByJob", ReplyAction="http://tempuri.org/IScheduleService/GetTriggersByJobResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.Trigger[] GetTriggersByJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/CreateTrigger", ReplyAction="http://tempuri.org/IScheduleService/CreateTriggerResponse")]
        void CreateTrigger(JasonSoft.Services.JobSchedule.ClientProxy.Trigger trigger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/DeleteTrigger", ReplyAction="http://tempuri.org/IScheduleService/DeleteTriggerResponse")]
        void DeleteTrigger(string triggerName, string triggerGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/UpdateTrigger", ReplyAction="http://tempuri.org/IScheduleService/UpdateTriggerResponse")]
        void UpdateTrigger(string oldTriggerName, string oldTriggerGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Trigger newTrigger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/UpdateJobAndTrigger", ReplyAction="http://tempuri.org/IScheduleService/UpdateJobAndTriggerResponse")]
        void UpdateJobAndTrigger(string oldJobName, string oldJobGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Job newJob, string oldTriggerName, string oldTriggerGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Trigger newTrigger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/RunJobOnceNow", ReplyAction="http://tempuri.org/IScheduleService/RunJobOnceNowResponse")]
        void RunJobOnceNow(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/EnableJob", ReplyAction="http://tempuri.org/IScheduleService/EnableJobResponse")]
        void EnableJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/DisableJob", ReplyAction="http://tempuri.org/IScheduleService/DisableJobResponse")]
        void DisableJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/StopRunningJob", ReplyAction="http://tempuri.org/IScheduleService/StopRunningJobResponse")]
        void StopRunningJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetHistoryByJob", ReplyAction="http://tempuri.org/IScheduleService/GetHistoryByJobResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.JobHistory[] GetHistoryByJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetStateByJob", ReplyAction="http://tempuri.org/IScheduleService/GetStateByJobResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.JobState GetStateByJob(string jobName, string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/GetStatesByJobGroup", ReplyAction="http://tempuri.org/IScheduleService/GetStatesByJobGroupResponse")]
        JasonSoft.Services.JobSchedule.ClientProxy.JobState[] GetStatesByJobGroup(string jobGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/ClearJobHistory", ReplyAction="http://tempuri.org/IScheduleService/ClearJobHistoryResponse")]
        void ClearJobHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleService/ClearJobsAndTriggers", ReplyAction="http://tempuri.org/IScheduleService/ClearJobsAndTriggersResponse")]
        void ClearJobsAndTriggers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IScheduleServiceChannel : JasonSoft.Services.JobSchedule.ClientProxy.IScheduleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ScheduleServiceClient : System.ServiceModel.ClientBase<JasonSoft.Services.JobSchedule.ClientProxy.IScheduleService>, JasonSoft.Services.JobSchedule.ClientProxy.IScheduleService
    {
        
        public ScheduleServiceClient()
        {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ScheduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.DateTime ScheduleJob(JasonSoft.Services.JobSchedule.ClientProxy.Job job, JasonSoft.Services.JobSchedule.ClientProxy.Trigger trigger)
        {
            return base.Channel.ScheduleJob(job, trigger);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.Job GetJob(string jobName, string jobGroupName)
        {
            return base.Channel.GetJob(jobName, jobGroupName);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.Job[] GetJobsByGroup(string jobGroupName)
        {
            return base.Channel.GetJobsByGroup(jobGroupName);
        }
        
        public void CreateJob(JasonSoft.Services.JobSchedule.ClientProxy.Job job)
        {
            base.Channel.CreateJob(job);
        }
        
        public void DeleteJob(string jobName, string jobGroupName)
        {
            base.Channel.DeleteJob(jobName, jobGroupName);
        }
        
        public void DeleteJobsByGroup(string jobGroupName)
        {
            base.Channel.DeleteJobsByGroup(jobGroupName);
        }
        
        public void UpdateJob(string oldJobName, string oldJobGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Job newJob)
        {
            base.Channel.UpdateJob(oldJobName, oldJobGroupName, newJob);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.Trigger GetTrigger(string triggerName, string triggerGroupName)
        {
            return base.Channel.GetTrigger(triggerName, triggerGroupName);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.Trigger[] GetTriggersByJob(string jobName, string jobGroupName)
        {
            return base.Channel.GetTriggersByJob(jobName, jobGroupName);
        }
        
        public void CreateTrigger(JasonSoft.Services.JobSchedule.ClientProxy.Trigger trigger)
        {
            base.Channel.CreateTrigger(trigger);
        }
        
        public void DeleteTrigger(string triggerName, string triggerGroupName)
        {
            base.Channel.DeleteTrigger(triggerName, triggerGroupName);
        }
        
        public void UpdateTrigger(string oldTriggerName, string oldTriggerGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Trigger newTrigger)
        {
            base.Channel.UpdateTrigger(oldTriggerName, oldTriggerGroupName, newTrigger);
        }
        
        public void UpdateJobAndTrigger(string oldJobName, string oldJobGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Job newJob, string oldTriggerName, string oldTriggerGroupName, JasonSoft.Services.JobSchedule.ClientProxy.Trigger newTrigger)
        {
            base.Channel.UpdateJobAndTrigger(oldJobName, oldJobGroupName, newJob, oldTriggerName, oldTriggerGroupName, newTrigger);
        }
        
        public void RunJobOnceNow(string jobName, string jobGroupName)
        {
            base.Channel.RunJobOnceNow(jobName, jobGroupName);
        }
        
        public void EnableJob(string jobName, string jobGroupName)
        {
            base.Channel.EnableJob(jobName, jobGroupName);
        }
        
        public void DisableJob(string jobName, string jobGroupName)
        {
            base.Channel.DisableJob(jobName, jobGroupName);
        }
        
        public void StopRunningJob(string jobName, string jobGroupName)
        {
            base.Channel.StopRunningJob(jobName, jobGroupName);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.JobHistory[] GetHistoryByJob(string jobName, string jobGroupName)
        {
            return base.Channel.GetHistoryByJob(jobName, jobGroupName);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.JobState GetStateByJob(string jobName, string jobGroupName)
        {
            return base.Channel.GetStateByJob(jobName, jobGroupName);
        }
        
        public JasonSoft.Services.JobSchedule.ClientProxy.JobState[] GetStatesByJobGroup(string jobGroupName)
        {
            return base.Channel.GetStatesByJobGroup(jobGroupName);
        }
        
        public void ClearJobHistory()
        {
            base.Channel.ClearJobHistory();
        }
        
        public void ClearJobsAndTriggers()
        {
            base.Channel.ClearJobsAndTriggers();
        }
    }
}
